"""Module 8: Team promotion/relegation."""

from .models import (
    TipoMovimentacao,
    MotivoMovimentacao,
    StatusConvite,
    ResultadoTemporada,
    HistoricoEquipe,
    Convite,
    Movimentacao,
    ConsequenciasMovimentacao,
    RelatorioPromocao,
)
from .regras import (
    RegraCategoria,
    REGRAS_CATEGORIAS,
    LEGACY_CATEGORY_ALIASES,
    canonicalizar_categoria_id,
    get_regra_categoria,
    get_categoria_destino_promocao,
    get_categoria_destino_rebaixamento,
    get_vagas_promocao,
    get_vagas_rebaixamento,
    get_budget_minimo_promocao,
    pode_ser_promovida,
    pode_ser_rebaixada,
    get_todas_categorias,
    get_categorias_por_tier,
    get_regras_rebaixamento_por_grupo,
)
from .avaliacao import (
    AvaliacaoEquipe,
    criar_resultado_temporada,
    avaliar_equipe,
    avaliar_todas_equipes,
    avaliar_elegibilidade_promocao,
    avaliar_elegibilidade_rebaixamento,
    avaliar_elegibilidade_convite,
)
from .consequencias import (
    PROMOCAO_CONFIG,
    REBAIXAMENTO_CONFIG,
    calcular_consequencias_promocao,
    calcular_consequencias_rebaixamento,
    aplicar_consequencias,
    simular_impacto,
)
from .convites import (
    criar_convite,
    equipe_decide_convite,
    processar_convites,
    gerar_convites_categoria,
)
from .historico import HistoricoGlobal, criar_movimentacao
from .clausulas import liberar_pilotos_por_rebaixamento
from .promocao_manager import (
    PromocaoManager,
    processar_promocoes_simples,
    aplicar_promocao_simples,
    aplicar_rebaixamento_simples,
    relatorio_to_dict,
)

__all__ = [
    "TipoMovimentacao",
    "MotivoMovimentacao",
    "StatusConvite",
    "ResultadoTemporada",
    "HistoricoEquipe",
    "Convite",
    "Movimentacao",
    "ConsequenciasMovimentacao",
    "RelatorioPromocao",
    "RegraCategoria",
    "REGRAS_CATEGORIAS",
    "LEGACY_CATEGORY_ALIASES",
    "canonicalizar_categoria_id",
    "get_regra_categoria",
    "get_categoria_destino_promocao",
    "get_categoria_destino_rebaixamento",
    "get_vagas_promocao",
    "get_vagas_rebaixamento",
    "get_budget_minimo_promocao",
    "pode_ser_promovida",
    "pode_ser_rebaixada",
    "get_todas_categorias",
    "get_categorias_por_tier",
    "get_regras_rebaixamento_por_grupo",
    "AvaliacaoEquipe",
    "criar_resultado_temporada",
    "avaliar_equipe",
    "avaliar_todas_equipes",
    "avaliar_elegibilidade_promocao",
    "avaliar_elegibilidade_rebaixamento",
    "avaliar_elegibilidade_convite",
    "PROMOCAO_CONFIG",
    "REBAIXAMENTO_CONFIG",
    "calcular_consequencias_promocao",
    "calcular_consequencias_rebaixamento",
    "aplicar_consequencias",
    "simular_impacto",
    "criar_convite",
    "equipe_decide_convite",
    "processar_convites",
    "gerar_convites_categoria",
    "HistoricoGlobal",
    "criar_movimentacao",
    "liberar_pilotos_por_rebaixamento",
    "PromocaoManager",
    "processar_promocoes_simples",
    "aplicar_promocao_simples",
    "aplicar_rebaixamento_simples",
    "relatorio_to_dict",
]
